-- MySQL Script generated by MySQL Workbench
-- Sat Jun 15 12:00:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Weather_History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Weather_History` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Weather_History` (
  `ID_weather` INT NOT NULL,
  `Tempertature_out` INT NOT NULL,
  `Temperature_IN` INT NOT NULL,
  `Humidity_OUT` INT NULL,
  `Humidity_IN` INT NULL,
  `Date_of_measure` DATETIME NULL,
  PRIMARY KEY (`ID_weather`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pots` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pots` (
  `ID_pots` INT NOT NULL,
  `Plant` VARCHAR(45) NULL,
  `Soil_humidity` INT NULL,
  `Soil_type` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_pots`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`icings_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`icings_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`icings_history` (
  `ID_icing` INT NOT NULL,
  `Icing_date` DATETIME NOT NULL,
  `Pots_ID` INT NOT NULL,
  PRIMARY KEY (`ID_icing`),
  INDEX `fk_icings_history_Pots_idx` (`Pots_ID` ASC) VISIBLE,
  CONSTRAINT `fk_icings_history_Pots`
    FOREIGN KEY (`Pots_ID`)
    REFERENCES `mydb`.`Pots` (`ID_pots`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Device` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Device` (
  `ID_device` INT NOT NULL,
  `Type_of_device` VARCHAR(100) NULL,
  `role` VARCHAR(100) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_device`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Error_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Error_log` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Error_log` (
  `ID_error` INT NOT NULL,
  `Reason` VARCHAR(100) NULL,
  `Date` DATETIME NULL,
  `Device_ID` INT NOT NULL,
  PRIMARY KEY (`ID_error`),
  INDEX `fk_Error_log_Device1_idx` (`Device_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Error_log_Device1`
    FOREIGN KEY (`Device_ID`)
    REFERENCES `mydb`.`Device` (`ID_device`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Akvarium_stats_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Akvarium_stats_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Akvarium_stats_history` (
  `ID` INT NOT NULL,
  `Temperature` INT NULL,
  `Level_of_water` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Akvarium_cleaning`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Akvarium_cleaning` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Akvarium_cleaning` (
  `ID_cleaning` INT NOT NULL,
  `Date_of_cleaning` DATETIME NULL,
  `Level_of_cleaning` INT NULL,
  PRIMARY KEY (`ID_cleaning`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
