-- MySQL Script generated by MySQL Workbench
-- Sat Jun 29 22:02:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smart-home-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smart-home-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart-home-db` DEFAULT CHARACTER SET utf8 ;
USE `smart-home-db` ;

-- -----------------------------------------------------
-- Table `smart-home-db`.`Weather_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Weather_History` (
  `ID_weather` INT NOT NULL AUTO_INCREMENT,
  `Tempertature_out` INT NOT NULL,
  `Temperature_IN` INT NOT NULL,
  `Humidity_OUT` INT NULL,
  `Humidity_IN` INT NULL,
  `Date_of_measure` DATETIME NULL,
  PRIMARY KEY (`ID_weather`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart-home-db`.`Pots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Pots` (
  `ID_pots` INT NOT NULL AUTO_INCREMENT,
  `Plant` VARCHAR(45) NULL,
  `Soil_humidity` INT NULL,
  `Soil_type` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_pots`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart-home-db`.`Icings_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Icings_history` (
  `ID_icing` INT NOT NULL AUTO_INCREMENT,
  `Icing_date` DATETIME NOT NULL,
  `Pots_ID` INT NOT NULL,
  PRIMARY KEY (`ID_icing`),
  INDEX `fk_icings_history_Pots_idx` (`Pots_ID` ASC) VISIBLE,
  CONSTRAINT `fk_icings_history_Pots`
    FOREIGN KEY (`Pots_ID`)
    REFERENCES `smart-home-db`.`Pots` (`ID_pots`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart-home-db`.`Device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Device` (
  `ID_device` INT NOT NULL AUTO_INCREMENT,
  `Type_of_device` VARCHAR(100) NULL,
  `role` VARCHAR(100) NULL,
  `location` VARCHAR(45) NULL,
  `IP_adress` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Status` TINYINT NULL,
  PRIMARY KEY (`ID_device`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart-home-db`.`Error_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Error_log` (
  `ID_error` INT NOT NULL AUTO_INCREMENT,
  `Reason` VARCHAR(100) NULL,
  `Date` DATETIME NULL,
  `Device_ID` INT NOT NULL,
  PRIMARY KEY (`ID_error`),
  INDEX `fk_Error_log_Device1_idx` (`Device_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Error_log_Device1`
    FOREIGN KEY (`Device_ID`)
    REFERENCES `smart-home-db`.`Device` (`ID_device`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart-home-db`.`Akvarium_stats_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Akvarium_stats_history` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Temperature` INT NULL,
  `Level_of_water` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart-home-db`.`Akvarium_cleaning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Akvarium_cleaning` (
  `ID_cleaning` INT NOT NULL AUTO_INCREMENT,
  `Date_of_cleaning` DATETIME NULL,
  `Level_of_cleaning` INT NULL,
  PRIMARY KEY (`ID_cleaning`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart-home-db`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Rooms` (
  `ID_Rooms` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Rooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart-home-db`.`Hue_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Hue_device` (
  `ID_Hue_device` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Number_of_light` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Hue_device`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart-home-db`.`Hue_Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-home-db`.`Hue_Room` (
  `Rooms_ID_Rooms` INT NOT NULL,
  `Hue_device_ID_Hue_device` INT NOT NULL,
  INDEX `fk_Hue_Room_Rooms1_idx` (`Rooms_ID_Rooms` ASC) VISIBLE,
  PRIMARY KEY (`Rooms_ID_Rooms`, `Hue_device_ID_Hue_device`),
  INDEX `fk_Hue_Room_Hue_device1_idx` (`Hue_device_ID_Hue_device` ASC) VISIBLE,
  CONSTRAINT `fk_Hue_Room_Rooms1`
    FOREIGN KEY (`Rooms_ID_Rooms`)
    REFERENCES `smart-home-db`.`Rooms` (`ID_Rooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hue_Room_Hue_device1`
    FOREIGN KEY (`Hue_device_ID_Hue_device`)
    REFERENCES `smart-home-db`.`Hue_device` (`ID_Hue_device`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
